site_name: Frontend Club
# site_url: https://frontendclub.dev

theme:
  name: dracula
  #logo: img/logo.png

extra_css:
  - css/extra.css
  #- css/dark.css

# contenido
nav:
  - Bienvenido: 'index.md'
  - Day 01: '01-day.md'
  - Day 02: '02-day.md'
  - Day 03: '03-day.md'
  - Day 04: '04-day.md'
  - Day 05: '05-day.md'
  - Day 06: '06-day.md'
  - Day 07: '07-day.md'
  - Day 08: '08-day.md'
  - Day 09: '09-day.md'
  - Day 10: '10-day.md'
  - Day 11: '11-day.md'
  - Day 12: '12-day.md'
  - Day 13: '13-day.md'
  - Day 14: '14-day.md'
  - Day 15: '15-day.md'
  - Day 16: '16-day.md'
  - Day 17: '17-day.md'
  - Day 18: '18-day.md'
  - Day 19: '19-day.md'
  - Day 20: '20-day.md'
  - Day 21: '21-day.md'
  - Day 22: '22-day.md'
  - Day 23: '23-day.md'
  - Day 24: '24-day.md'
  - Day 25: '25-day.md'
  - Day 26: '26-day.md'
  - Day 27: '27-day.md'
  - Day 28: '28-day.md'
  - Day 29: '29-day.md'
  - Day 30: '30-day.md'
  - Day 31: '31-day.md'
  - Day 32: '32-day.md'
  - Day 33: '33-day.md'
  - Day 34: '34-day.md'
  - Day 35: '35-day.md'
  - Day 36: '36-day.md'
  - Day 37: '37-day.md'
  - Day 38: '38-day.md'
  - Day 39: '39-day.md'
  - Day 40: '40-day.md'