site_name: Frontend Club
# site_url: https://frontendclub.dev

theme:
  name: dracula
  #logo: img/logo.png

  palette:
    primary: yellow
    accent: light blue
    locale: en
  toggle:
     icon: material/weather-sunny  # Icono de cambio de tema
     name: Switch to light mode  # Texto del botón

extra_css:
  - css/extra.css
  #- css/dark.css

# extra_javascript:
#   - js/theme-toggle.js

# plugins:
#   - revealjs:
#       theme: "black"  # or any other theme you prefer

# contenido
nav:
  - Bienvenido: 'index.md'
  - Day 01: '01-day.md'
  - Day 02: '02-day.md'
  - Day 03: '03-day.md'
  - Day 04: '04-day.md'
  - Day 05: '05-day.md'
  - Day 06: '06-day.md'
  - Day 07: '07-day.md'
  - Day 08: '08-day.md'
  - Day 09: '09-day.md'
  - Day 10: '10-day.md'
  - Day 11: '11-day.md'
  - Day 12: '12-day.md'
  - Day 13: '13-day.md'
  - Day 14: '14-day.md'
  - Day 15: '15-day.md'
  - Day 16: '16-day.md'
  - Day 17: '17-day.md'
  - Day 18: '18-day.md'
  - Day 19: '19-day.md'
  - Day 20: '20-day.md'