site_name: Frontend Club
# site_url: https://frontendclub.dev

theme:
  name: dracula
  #logo: img/logo.png

extra_css:
  - css/extra.css
  #- css/dark.css

# contenido
nav:
  - Bienvenido: 'index.md'
  - Day 01: '01-day.md'
  - Day 02: '02-day.md'
  - Day 03: '03-day.md'
  - Day 04: '04-day.md'
  - Day 05: '05-day.md'
  - Day 06: '06-day.md'
  - Day 07: '07-day.md'
  - Day 08: '08-day.md'
  - Day 09: '09-day.md'
  - Day 10: '10-day.md'
  - Day 11: '11-day.md'
  - Day 12: '12-day.md'
  - Day 13: '13-day.md'
  - Day 14: '14-day.md'
  - Day 15: '15-day.md'
  - Day 16: '16-day.md'
  - Day 17: '17-day.md'
  - Day 18: '18-day.md'
  - Day 19: '19-day.md'
  - Day 20: '20-day.md'
  - Day 21: '21-day.md'
  - Day 22: '22-day.md'
  - Day 23: '23-day.md'
  - Day 24: '24-day.md'
  - Day 25: '25-day.md'
  - Day 26: '26-day.md'
  - Day 27: '27-day.md'
  - Day 28: '28-day.md'
  - Day 29: '29-day.md'
  - Day 30: '30-day.md'
  - Day 31: '31-day.md'
  - Day 32: '32-day.md'
  - Day 33: '33-day.md'
  - Day 34: '34-day.md'
  - Day 35: '35-day.md'
  - Day 36: '36-day.md'
  - Day 37: '37-day.md'
  - Day 38: '38-day.md'
  - Day 39: '39-day.md'
  - Day 40: '40-day.md'
  - Day 41: '41-day.md'
  - Day 42: '42-day.md'
  - Day 43: '43-day.md'
  - Day 44: '44-day.md'
  - Day 45: '45-day.md'
  - Day 46: '46-day.md'
  - Day 47: '47-day.md'
  - Day 48: '48-day.md'
  - Day 49: '49-day.md'
  - Day 50: '50-day.md'
  - Day 51: '51-day.md'
  - Day 52: '52-day.md'
  - Day 53: '53-day.md'
  - Day 54: '54-day.md'
  - Day 55: '55-day.md'
  - Day 56: '56-day.md'
  - Day 57: '57-day.md'
  - Day 58: '58-day.md'
  - Day 59: '59-day.md'
  - Day 60: '60-day.md'
  - Day 61: '61-day.md'
  - Day 62: '62-day.md'
  - Day 63: '63-day.md'
  - Day 64: '64-day.md'
  - Day 65: '65-day.md'
  - Day 66: '66-day.md'
  - Day 67: '67-day.md'
  - Day 68: '68-day.md'
  - Day 69: '69-day.md'
  - Day 70: '70-day.md'
  - Day 71: '71-day.md'
  - Day 72: '72-day.md'
  - Day 73: '73-day.md'
  - Day 74: '74-day.md'
  - Day 75: '75-day.md'
  - Day 76: '76-day.md'
  - Day 77: '77-day.md'
  - Day 78: '78-day.md'
  - Day 79: '79-day.md'
  - Day 80: '80-day.md'
  - Day 81: '81-day.md'
  - Day 82: '82-day.md'
  - Day 83: '83-day.md'
  - Day 84: '84-day.md'
  - Day 85: '85-day.md'
  - Day 86: '86-day.md'
  - Day 87: '87-day.md'
  - Day 88: '88-day.md'
  - Day 89: '89-day.md'
  - Day 90: '90-day.md'
  - Day 91: '91-day.md'
  - Day 92: '92-day.md'
  - Day 93: '93-day.md'
  - Day 94: '94-day.md'
  - Day 95: '95-day.md'
  - Day 96: '96-day.md'
  - Day 97: '97-day.md'
  - Day 98: '98-day.md'
  - Day 99: '99-day.md'
  - Day 100: '100-day.md'