site_name: Frontend Club
# site_url: https://frontendclub.dev

theme:
  name: readthedocs
  #logo: img/logo.png

  palette:
    primary: slate
    accent: indigo
    accent: pink
    locale: en
  toggle:
     icon: material/weather-sunny  # Icono de cambio de tema
     name: Switch to light mode  # Texto del botón

# contenido
nav:
  - Bienvenido: 'index.md'
  - Day 01: '01-day.md'